#!/bin/sh -e

set -e

jdk_tools='appletviewer extcheck idlj jar jarsigner javac javadoc javah javap jcmd jconsole jdb jhat jinfo jmap jps jrunscript jsadebugd jstack jstat jstatd native2ascii rmic schemagen serialver wsgen wsimport xjc'
basedir=/usr/lib/jvm/java-7-dcevm-amd64


if [ "$1" = "remove" ] || [ "$1" = "deconfigure" ]; then
    for i in $jdk_tools; do
	update-alternatives --remove $i $basedir/bin/$i
    done
fi


